const API_BASE=(window.BLIN_API_BASE||'').replace(/\/$/,'');
const state={guilds:[],guild:null,modules:{},objects:{},me:null};
async function api(path,options={}){const r=await fetch(`${API_BASE}${path}`,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();if(!r.ok){let message=text;try{const data=JSON.parse(text);message=data.error||message}catch{}throw new Error(`${r.status} ${message}`)}return r.status===204?null:JSON.parse(text)}
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const guildId=v=>String(v??'').trim();
const labels={applications:'Заявки',vacations:'Отпуска',contracts:'Контракты',discipline:'Дисциплина',dm_notifications:'DM-уведомления',reaction_roles:'Роли через кнопки'};
async function loadMe(){const me=await api('/api/me');state.me=me;document.querySelectorAll('[data-admin-link]').forEach(e=>e.hidden=!me.site_admin);return me}
async function loadDashboard(){try{const me=await loadMe();if(!me.user){location.href=`${API_BASE}/auth/discord`;return}const guilds=await api('/api/guilds');const exactIds=Array.isArray(me.guild_ids)?me.guild_ids.map(guildId):[];state.guilds=guilds.map(g=>{const numeric=Number(g.id);const exact=exactIds.find(id=>Number(id)===numeric);return {...g,id:exact||guildId(g.id)}});renderGuilds();if(state.guilds[0])await selectGuild(state.guilds[0].id);setStatus('Бот подключён',true)}catch(e){console.error('Dashboard load error:',e);if(e.message.startsWith('401 ')){location.href=`${API_BASE}/auth/discord`;return}setStatus(e.message||'API недоступен',false)}}
function renderGuilds(){const el=document.querySelector('#guild-list');if(!el)return;el.innerHTML=state.guilds.length?state.guilds.map(g=>{const id=guildId(g.id);return `<button class="guild-option" data-id="${esc(id)}"><span class="server-avatar">${esc(g.name[0]||'B')}</span>${esc(g.name)}</button>`}).join(''):'<div class="empty">Нет доступных серверов</div>';el.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>selectGuild(guildId(b.dataset.id)));}
async function selectGuild(id){id=guildId(id);state.guild=state.guilds.find(g=>guildId(g.id)===id);document.querySelectorAll('.guild-option').forEach(b=>b.classList.toggle('active',guildId(b.dataset.id)===id));if(!state.guild)return;setStatus('Загрузка сервера…',true);try{const encoded=encodeURIComponent(guildId(state.guild.id));const [modules,objects]=await Promise.all([api(`/api/guilds/${encoded}/modules`),api(`/api/guilds/${encoded}/objects`)]);state.modules=modules;state.objects=objects;renderServer();setStatus('Бот подключён',true)}catch(e){console.error(`Guild ${id} load error:`,e);setStatus(`Ошибка загрузки сервера: ${e.message||'неизвестная ошибка'}`,false)}}
function renderServer(){document.querySelector('#server-name').textContent=state.guild.name;document.querySelector('#member-count').textContent=state.guild.member_count??'—';const channels=Array.isArray(state.objects.channels)?state.objects.channels:[];const categories=Array.isArray(state.objects.categories)?state.objects.categories:[];const roles=Array.isArray(state.objects.roles)?state.objects.roles:[];document.querySelector('#object-count').textContent=`${channels.length} каналов · ${categories.length} категорий · ${roles.length} ролей`;const list=document.querySelector('#module-list');list.innerHTML=Object.entries(state.modules).map(([n,m])=>`<div class="module-row"><div><strong>${esc(labels[n]||n)}</strong><small>${m.enabled?'Модуль включён':'Модуль выключен'}</small></div><button class="toggle ${m.enabled?'on':''}" data-module="${n}"><i></i></button></div>`).join('');list.querySelectorAll('[data-module]').forEach(b=>b.onclick=async()=>{const n=b.dataset.module,m=!state.modules[n].enabled;try{await api(`/api/guilds/${encodeURIComponent(guildId(state.guild.id))}/modules`,{method:'PUT',body:JSON.stringify({module:n,enabled:m,settings:state.modules[n].settings||{}})});state.modules[n].enabled=m;renderServer()}catch(e){console.error(e);setStatus(`Ошибка сохранения: ${e.message||'неизвестная ошибка'}`,false)}})}
function setStatus(t,ok){const e=document.querySelector('#api-status');if(e){e.textContent=t;e.className=ok?'online':'offline'}}
async function logout(){try{await api('/api/logout',{method:'POST'})}finally{location.href='index.html'}}
function init(){document.querySelectorAll('[data-login]').forEach(e=>e.onclick=()=>location.href=`${API_BASE}/auth/discord`);document.querySelector('[data-logout]')?.addEventListener('click',logout);document.querySelector('[data-demo]')?.addEventListener('click',()=>document.querySelector('#preview')?.scrollIntoView({behavior:'smooth'}));if(document.body.dataset.dashboard==='true')loadDashboard()}
window.Blin={api,loadDashboard,loadMe};document.addEventListener('DOMContentLoaded',init);
